name: Build and Deploy TWA

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Initialize Bubblewrap Project
        run: |
          export BUBBLEWRAP_ACCEPT_LICENSES=true
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
          # Usamos un heredoc para responder a los prompts de Bubblewrap:
          bubblewrap init --manifest=https://unrivaled-medovik-6879ce.netlify.app/manifest.json --overwrite <<EOF
n
$JAVA_HOME
n
EOF

      - name: Build APK
        run: bubblewrap build

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: twa-apk
          path: ./app-release-signed.apk
