name: Build and Deploy

on:
  push:
    branches:
      - main  # Asegúrate de que tu rama principal sea 'main' o 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16  # Sin comillas para evitar errores

      - name: Install Bubblewrap CLI globally
        run: npm install -g @bubblewrap/cli

      - name: Initialize Bubblewrap project
        run: |
          echo -e "Y\nY\n" | bubblewrap init --manifest=https://unrivaled-medovik-6879ce.netlify.app/manifest.json --overwrite

      - name: Build APK
        run: bubblewrap build

      # Subir el APK como un artefacto descargable en GitHub Actions
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: ./app-release-signed.apk  # Ajusta la ruta según donde Bubblewrap genere el APK
